site_name: Heroic
site_url: https://yllumi.github.io/heroic/
theme: 
  name: material
  logo: assets/logo-white.png
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Raleway
repo_url: https://github.com/yllumi/heroic
extra_css:
  - css/heroic.css
nav:
  - Introduction: intro.md
  - Installation: installation.md
